application: sockmarket
version: 0-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /.*
  script: app.Controller.application

libraries:
- name: numpy
  version: "1.6.1"
